# Goal
float64 target_lat_deg
float64 target_lon_deg
float32 distance_agl_m
float32 speed_m_s
float32 heading_offset_deg
float32 goal_yaw_deg
---
# Result
bool success
---
# Feedback
float32 progress_percent